gitops-runtime:
  global:
    codefresh:
      accountId: 6834b69e913d66e947302f3b
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
      isConfigurationRuntime: true
